defaults: &defaults
  additional_info: true
  contact_phone: true
  description: true
  electricity: true
  light: true
  fire: false
  noise: true
  nature: false
  moop: false
  plan: false
  cocreation: true
  neighbors: false
  budgetplan: true
  seeking_members: false
  granting: false
  user_authentication_codes: false
  add_to_list: false
  granting_active: false
  footer_text: false
  footer_logo: false

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults